setup:
  channels: &setup_channels
    - defaults
  dependencies: &setup_dependencies
    - python
    - setuptools
    - numpy

production:
  channels: &production_channels
    - conda-forge
    - *setup_channels
  dependencies: &production_dependencies
    - *setup_dependencies
    - scipy
    - openbabel
    - matplotlib
    - rdkit

test:
  channels: &test_channels
    - *production_channels
  dependencies: &test_dependencies
    - *production_dependencies

development:
  channels:
    - *production_channels
    - uibcdf
  dependencies:
    - *production_dependencies
    - *test_dependencies
    - pyyaml
    - seaborn
    - chembl_webresource_client
    - jupyterlab

